---
- name: Fetch Mainframe Syslog using ZOAU pcon
  hosts: vs01
  gather_facts: no
  collections:
    - ibm.ibm_zos_core

  # The environment variable is now mandatory and must be passed from the AWX
  # Job Template, for example, as an empty dictionary '{}' if no vars are needed.
  vars:
    environment: "{{ environment_vars }}"

  tasks:
    # ----------------------------------------------------------------------
    # STEP 1: Get date string from mainframe by executing a pre-existing script.
    # ----------------------------------------------------------------------
    - name: Get current date string from mainframe by executing date.sh
      ibm.ibm_zos_core.zos_script:
        cmd: "./date.sh"
        executable: /bin/sh
      register: mainframe_time_raw

    # ----------------------------------------------------------------------
    # STEP 2: Parse the date string and calculate the start epoch.
    # ----------------------------------------------------------------------
    - name: Parse date string and calculate the start time epoch
      set_fact:
        start_epoch: "{{ ((mainframe_time_raw.stdout | to_datetime('%a %b %d %H:%M:%S  %Y')).strftime('%s') | int) - (hours_ago | int) * 3600 }}"

    # ----------------------------------------------------------------------
    # STEP 3: Format the calculated start time for the pcon command.
    # ----------------------------------------------------------------------
    - name: Format start date and time for the pcon command
      set_fact:
        start_date_yyddd: "{{ '%y%j' | strftime(start_epoch) }}"
        start_time_hhmmss: "{{ '%H%M%S' | strftime(start_epoch) }}"

    # ----------------------------------------------------------------------
    # STEP 4: Create a temporary pcon script on the controller and copy it to the host.
    # ----------------------------------------------------------------------
    - name: Create and copy a temporary pcon script to the mainframe
      ibm.ibm_zos_core.zos_copy:
        content: |
          #!/bin/sh
          pcon -s {{ start_date_yyddd }} {{ start_time_hhmmss }}
        dest: "/tmp/pcon_temp.sh"
        mode: '0755'
      register: copy_result

    # ----------------------------------------------------------------------
    # STEP 5: Execute the newly created pcon_temp.sh script on the host.
    # ----------------------------------------------------------------------
    - name: Execute the temporary pcon script to retrieve log content
      ibm.ibm_zos_core.zos_script:
        cmd: "{{ copy_result.dest }}"
        executable: /bin/sh
      register: pcon_script_output

    # ----------------------------------------------------------------------
    # STEP 6: Clean up the temporary script from the host.
    # ----------------------------------------------------------------------
    - name: Remove temporary script from the mainframe
      ibm.ibm_zos_core.zos_file:
        path: "{{ copy_result.dest }}"
        state: absent

    # ----------------------------------------------------------------------
    # STEP 7: Set the captured stdout as a job artifact for the AWX client.
    # ----------------------------------------------------------------------
    - name: Set the log content as a job artifact for AWX
      set_stats:
        data:
          log_content: "{{ pcon_script_output.stdout }}"

