---
- name: Fetch Mainframe Syslog using ZOAU pcon
  hosts: vs01
  gather_facts: no
  collections:
    - ibm.ibm_zos_core
  environment: "{{ environment_vars }}"
  tasks:
    - name: Execute Date command and convert output to UTF-8
      ansible.builtin.shell: "date | iconv -f ibm-1047 -t iso8859-1"
      register: mainframe_time_raw

    - name: Parse date string and calculate the start time epoch
      set_fact:
        start_epoch: "{{ ((mainframe_time_raw.stdout | to_datetime('%a %b %d %H:%M:%S  %Y')).strftime('%s') | int) - (hours_ago | int) * 3600 }}"

    - name: Create pcon command 
      ansible.builtin.shell: "pcon -s {{ '%y%j' | strftime(start_epoch) }} {{ '%H%M%S' | strftime(start_epoch) }} | iconv -f ibm-1047 -t iso8859-1 "
      register: pcon_script_output

    - name: Set the log content as a job artifact for AWX
      set_stats:
        data:
          log_content: "{{ pcon_script_output.stdout }}"

