- name: Fetch Mainframe Syslog using ZOAU pcon
  hosts: vs01
  gather_facts: no
  collections:
    - ibm.ibm_zos_core
  environment: "{{ environment_vars }}"
  vars:
    # Define the number of hours to go back.
    # This can be easily changed or overridden by an extra variable in AWX.
    hours_ago: 2
  tasks:
    - name: "Fetch the last {{ hours_ago }} hour(s) of syslog"
#      ansible.builtin.shell: "pcon -t {{ hours_ago | int * 60 }} | iconv -f ibm-1047 -t iso8859-1"
      ansible.builtin.shell: "pcon -w | iconv -f ibm-1047 -t iso8859-1"

      register: pcon_script_output

    - name: Set the log content as a job artifact for AWX
      set_stats:
        data:
          log_content: "{{ pcon_script_output.stdout }}"
