---
- hosts: vs01
  collections:
    - ibm.ibm_zos_core
  gather_facts: false

  vars:
  environment: "{{ environment_vars }}"

  tasks:
    - name: "Fail if jobname is not provided"
      ansible.builtin.fail:
        msg: "The 'jobname' variable was not provided. Please supply it as an extra variable in your AWX job template."
      when: jobname is not defined or jobname == ""

    - name: "Get all spool files for job {{ jobname }}"
      ibm.ibm_zos_core.zos_job_output:
        job_name: "{{ jobname | upper }}"
      register: job_output_result

    # --- THIS IS THE NEW WORKAROUND ---
    # We will print the entire job log directly to the Ansible output.
    # We add start and end markers to make it easy for our Python code to find it.
    - name: "Display Mainframe Job Output"
      ansible.builtin.debug:
        msg: |
          --- BEGIN MAINFRAME JOB LOG ---
          {% if job_output_result.jobs is defined and job_output_result.jobs | length > 0 %}
          {% for line in job_output_result.jobs[0].ddnames[0].content %}
          {{ line }}
          {% endfor %}
          {% else %}
          JOB NOT FOUND: No job output found for '{{ jobname | upper }}'.
          {% endif %}
          --- END MAINFRAME JOB LOG ---
