---
- hosts: vs01
  collections:
    - ibm.ibm_zos_core
  gather_facts: false

  vars:
  environment: "{{ environment_vars }}"

  tasks:
    - name: "Fail if jobname is not provided"
      ansible.builtin.fail:
        msg: "The 'jobname' variable was not provided. Please supply it as an extra variable in your AWX job template."
      when: jobname is not defined or jobname == ""

    - name: "Get all spool files for job {{ jobname }}"
      ibm.ibm_zos_core.zos_job_output:
        job_name: "{{ jobname | upper }}"
      register: job_output_result

    - name: "Prepare the job output, or a 'not found' message"
      ansible.builtin.set_fact:
        full_job_log: |
          {% if job_output_result.jobs is defined and job_output_result.jobs | length > 0 %}
          {{ job_output_result.jobs[0].ddnames | to_nice_json }}
          {% else %}
          JOB NOT FOUND: No job output found for '{{ jobname | upper }}'. The job may not exist, may have purged, or you may lack permissions to view it.
          {% endif %}

    - name: "Return the entire job output as an artifact to AWX"
      ansible.builtin.set_stats:
        data:
          job_output: "{{ full_job_log }}"
        per_host: no
